version: '3'
services:
  app:
    image: itopstiendeo/devops-eval-test-1-app:v1
    ports:
    - "5000:5000"
    depends_on:
    - redis
    - logstash
    - kibana
  redis:
    image: "redis:alpine"
    expose:
    - "6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
    - discovery.type=single-node
    ports:
    - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
    - 5601:5601
    depends_on:
    - elasticsearch
  logstash:
    image: docker.elastic.co/logstash/logstash:7.17.0
    volumes:
    - ./logstash/:/etc/logstash
    command: logstash -f /etc/logstash/logstash.conf
    ports:
    - 5514:5514/udp
    depends_on:
    - elasticsearch